# Generated by Django 3.1.7 on 2021-04-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcion',
            old_name='region_texto',
            new_name='candidato',
        ),
        migrations.RenameField(
            model_name='opcion',
            old_name='pregunta',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region_texto',
            new_name='candidato',
        ),
    ]
