# Generated by Django 3.1.7 on 2021-04-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_auto_20210402_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='candidato',
            new_name='region_opcion',
        ),
    ]
